#!/usr/bin/env bash
# The script configures a new Ubuntu machine to install Nginx.

# Install Nginx
apt update
apt install nginx -y

# Open port 80 for listening
ufw allow 'Nginx HTTP'

# Index html constains string
echo 'Hello World!' > /var/www/html/index.html

# Error html contains error message
echo "Ceci n'est pas une page" > /var/www/html/404.html

# Configure server
replacement='server {\nrewrite \^\/redirect_me\/ https:\/\/www.youtube.com permanent;\nerror_page 404 \/404.html;'
sed -i 's/^server\s*{/'"$replacement"'/g' /etc/nginx/sites-available/default
rm -f /etc/nginx/sites-enabled/default
sudo ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default

# Restart Nginx
service nginx restart
