#!/usr/bin/env bash
#show your pid made easy

for pid in /proc/*/; do
    pid=${pid%*/}
    pid=${pid##*/}

    if [[ -f "/proc/$pid/cmdline" ]]; then
        cmdline=$(tr -d '\0' </proc/"$pid"/cmdline)
        if [[ $cmdline == *"bash"* ]]; then
            echo "$pid bash"
        fi
    fi
done
