#!/usr/bin/env bash
#Nested loop in bash

hour=0
min=1

while [ "$hour" -le 12 ]
do
	echo "Hour: $hour"
	while [ "$min" -le 59 ]
	do
		echo "$min"
		min=$((min + 1))
	done
	min=0
	hour=$((hour + 1))
done
