#!/usr/bin/env bash
#more conditional statements in bash

doc="school"

if [ -e "$doc" ]
then
	echo "$doc file exists"
	if [ ! -s "$doc" ]
	then
		echo "$doc file is empty"
	else
		echo "$doc file is not empty"
	fi
	if [ -f "$doc" ]
	then
		echo "$doc file is a regular file"
	fi
else
	echo "$doc file does not exist"
fi
